on: workflow_dispatch
jobs:
  push-to-blog:
    runs-on: ubuntu-22.04
    steps:
      - name: Push directory to another repository
        # You may pin to the exact commit or the version.
        # uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{secrets.BLOG_PAT}}
        with:
          # Source before directory from the origin directory
          #source-before-directory: # optional
          # Source directory from the origin directory
          source-directory: 'src'
          # Name of the destination username/organization
          destination-github-username: 'ndc'
          # Destination repository
          destination-repository-name: 'ndc.github.io'
          # Email for the git commit
          user-email: 'endy_c@yahoo.com'
          # Github server
          #github-server: # optional, default is github.com
          # [Optional] Name for the git commit. Defaults to the destination username/organization name
          #user-name: # optional, default is 
          # [Optional] Username/organization for the destination repository
          #destination-repository-username: # optional, default is 
          # [Optional] set target branch name for the destination repository. Defaults to "main"
          target-branch: 'master'
          # [Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
          #commit-message: # optional, default is Update from ORIGIN_COMMIT
          # [Optional] The directory to wipe and replace in the target repository
          target-directory: '/apps/colorpicker'
          # [Optional] create target branch if not exist. Defaults to `false`
          #create-target-branch-if-needed: # optional
